# Generated by Django 4.0.6 on 2022-07-07 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spot', '0004_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.type')),
            ],
        ),
    ]
