# Generated by Django 4.0.6 on 2022-07-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
        ('hotel', '0002_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='spot_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot'),
        ),
    ]
