# Generated by Django 4.0.6 on 2022-07-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_spot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address_line',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cordinate_lattitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cordinate_longitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='short_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thana',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='upzila',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
