# Generated by Django 4.0.6 on 2022-07-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_address_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_Attribute',
            fields=[
                ('attribute_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_no', models.IntegerField(default=0)),
                ('room_type', models.CharField(max_length=100, null=True)),
                ('hotel_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Attribute',
            fields=[
                ('attribute_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPriceInfo',
            fields=[
                ('price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('factor', models.FloatField(default=1)),
                ('start_time', models.DateTimeField(null=True)),
                ('room_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Attribute_Table',
            fields=[
                ('room_attribute_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, null=True)),
                ('attribute_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.room_attribute')),
                ('room_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRatingInfo',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('factor', models.FloatField(default=1)),
                ('start_time', models.DateTimeField(null=True)),
                ('hotel_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Attribute_Table',
            fields=[
                ('hotel_attribute_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100, null=True)),
                ('attribute_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel_attribute')),
                ('hotel_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
