# Generated by Django 4.0.6 on 2022-07-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_attribute_room_room_attribute_roompriceinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompriceinfo',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
