export const categoryList = [
  {
    id: 1,
    value: 'place',
    label: '🚩 Places',
  },
  {
    id: 2,
    value: 'spot',
    label: '🏖️ Spots',
  },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'Dhuppani',
    serviceTime: '45-60min',
    deliveryFee: 3.44,
    category: 'spot',
    place: 'waterfall',
    food: 'chinese',
    activity: 'trekking',
    rating: 5,
    price: 2500,
    coverSrc: '/images/spots/dhuppani_rangamati.jpg',
  },
  {
    id: 2,
    title: 'Ratargul',
    serviceTime: '15-20min',
    deliveryFee: 4.94,
    category: 'spot',
    place: 'forest',
    food: 'bengali',
    activity: 'boat riding',
    rating: 4,
    price: 1000,
    coverSrc: '/images/spots/ratargul_sylhet.jpg',
  },
  {
    id: 3,
    title: 'Dumlong',
    serviceTime: '30-22min',
    deliveryFee: 4.94,
    category: 'spot',
    place: 'mountain',
    food: 'italian',
    activity: 'trekking',
    rating: 3,
    price: 2000,
    coverSrc: '/images/spots/dumlong_rangamati.png',
  },
  {
    id: 4,
    title: 'Kaptai Lake',
    serviceTime: '10-18min',
    deliveryFee: 2.14,
    category: 'spot',
    place: 'lake',
    food: 'bengali',
    activity: 'kayaking',
    rating: 1,
    price: 1800,
    coverSrc: '/images/spots/kaptai_lake_rangamati.jpg',
  },
  {
    id: 5,
    title: 'Himchori',
    serviceTime: '25-30min',
    deliveryFee: 6.79,
    category: 'spot',
    place: 'mountain',
    food: 'chinese',
    activity: '',
    rating: 5,
    price: 2000,
    coverSrc: '/images/spots/himchori_cox_bazar.jpg',
  },
  {
    id: 6,
    title: 'Sakahaphong',
    serviceTime: '5-15min',
    deliveryFee: 2.87,
    category: 'spot',
    place: 'mountain',
    food: 'upojati food',
    activity: 'trekking',
    rating: 5,
    price: 3500,
    coverSrc: '/images/spots/sakahaphong_bandorban.jpg',
  },
  {
    id: 7,
    title: 'Nafakhum',
    serviceTime: '50-65min',
    deliveryFee: 8.5,
    category: 'spot',
    place: 'waterfall',
    food: 'upojati food',
    activity: 'trekking',
    rating: 2,
    price: 2200,
    coverSrc: '/images/spots/nafakhum_bandarban.jpg',
  },
  {
    id: 8,
    title: 'Alutila Hill',
    serviceTime: '10-15min',
    deliveryFee: 1.8,
    category: 'spot',
    place: 'mountain',
    food: 'upojati food',
    activity: 'trekking',
    rating: 1,
    price: 1900,
    coverSrc: '/images/spots/alutila_hill_khagrachori.jpg',
  },
  {
    id: 9,
    title: 'Tetulia tea garden',
    serviceTime: '12-18min',
    deliveryFee: 3.33,
    category: 'spot',
    place: 'tea Garden',
    food: '',
    activity: '',
    rating: 4,
    price: 2750,
    coverSrc: '/images/spots/tetulia_tea_garden_panchagarh.jpg',
  },
  {
    id: 10,
    title: 'Hiron point',
    serviceTime: '30-38min',
    deliveryFee: 1.9,
    category: 'spot',
    place: 'forest',
    food: '',
    activity: '',
    rating: 2,
    price: 4350,
    coverSrc: '/images/spots/hironpoint_sundarban.jpg',
  },
  {
    id: 11,
    title: 'Madhutila Eco park',
    serviceTime: '16-20min',
    deliveryFee: 4.1,
    category: 'spot',
    place: 'eco park',
    food: 'bengali',
    activity: '',
    rating: 3,
    price: 3300,
    coverSrc: '/images/spots/madhutila_eco_park_mymensingh.jpg',
  },
  {
    id: 12,
    title: 'Niladri lake',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'spot',
    place: 'lake',
    food: 'chinese',
    activity: 'boat riding',
    rating: 2,
    price: 4100,
    coverSrc: '/images/spots/niladri_lake_sunamgonj.jpg',
  },
  {
    id: 13,
    title: 'Bandorban',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'place',
    place: 'waterfall',
    food: 'upojati food',
    activity: 'trekking',
    rating: 2,
    price: 4100,
    coverSrc: '/images/places/bandorban.jpg',
  },
  {
    id: 14,
    title: 'Cox\'s bazar',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'place',
    place: 'beach',
    food: 'bengali',
    activity: 'water bike',
    rating: 2,
    price: 4100,
    coverSrc: '/images/places/cox_bazar.jpg',
  },
  {
    id: 15,
    title: 'Kuakata',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'place',
    place: 'beach',
    food: 'bengali',
    activity: 'water bike',
    rating: 2,
    price: 4100,
    coverSrc: '/images/places/kuakata.jpg',
  },
  {
    id: 16,
    title: 'Rangamati',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'place',
    place: 'waterfall',
    food: 'bengali',
    activity: 'trekking',
    rating: 2,
    price: 4100,
    coverSrc: '/images/places/rangamati.jpg',
  },
  {
    id: 17,
    title: 'Shundarban',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'place',
    place: 'forest',
    food: '',
    activity: '',
    rating: 2,
    price: 4100,
    coverSrc: '/images/places/sundarban.jpg',
  },
  {
    id: 18,
    title: 'Sylhet',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'place',
    place: 'waterfall',
    food: 'bengali',
    activity: 'boat riding',
    rating: 2,
    price: 4100,
    coverSrc: '/images/places/sylhet.jpg',
  },
];
