# Generated by Django 3.2.14 on 2022-08-26 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=1000, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('cordinate_lattitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('cordinate_longitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./spot/images')),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=1000, null=True)),
                ('address_line', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('thana', models.CharField(max_length=50, null=True)),
                ('upzila', models.CharField(max_length=50, null=True)),
                ('cordinate_lattitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('cordinate_longitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./spot/images')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='spot.place')),
            ],
        ),
        migrations.CreateModel(
            name='SpotType_Table',
            fields=[
                ('type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Spot',
            fields=[
                ('user_spot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Place',
            fields=[
                ('user_place_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.place')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotRatingInfo',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('factor', models.FloatField(default=1)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_Type',
            fields=[
                ('spot_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
                ('type_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spottype_table')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_Food',
            fields=[
                ('spot_food_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('food_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_Activity',
            fields=[
                ('spot_activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Spot',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Place',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spot.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceRatingInfo',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('factor', models.FloatField(default=1)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('place_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.place')),
            ],
        ),
    ]
