# Generated by Django 4.0.6 on 2022-07-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_place_alter_spot_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='place_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.place'),
        ),
        migrations.CreateModel(
            name='PlaceRatingInfo',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('factor', models.FloatField(default=1)),
                ('start_time', models.DateTimeField(null=True)),
                ('place_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.place')),
            ],
        ),
    ]
