# Generated by Django 4.0.6 on 2022-07-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_restaurant_foodratinginfo_foodpriceinfo'),
        ('user', '0001_initial'),
        ('activity', '0002_activity_agency_agency_activityratinginfo_and_more'),
        ('spot', '0004_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Spot',
            fields=[
                ('user_spot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_Type',
            fields=[
                ('spot_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
                ('type_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.type')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_Food',
            fields=[
                ('spot_food_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('food_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
            ],
        ),
        migrations.CreateModel(
            name='Spot_Activity',
            fields=[
                ('spot_activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('spot_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spot.spot')),
            ],
        ),
    ]
