# Generated by Django 4.0.2 on 2022-07-14 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spot', '0005_user_spot_spot_type_spot_food_spot_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeratinginfo',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='spot.place'),
        ),
        migrations.AlterField(
            model_name='user_spot',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
