export const categoryList = [
  {
    id: 1,
    value: 'place',
    label: '🚩 Places',
  },
  {
    id: 2,
    value: 'spot',
    label: '🏖️ Spots',
  },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];

export let dataList = [


  {
    id: 4,
    title: 'wharf seafood',
    desc: "abcd    ed",
    serviceTime: '10-18min',
    deliveryFee: 2.14,
    category: 'place',
    place: 'mountain',
    food: 'bengali',
    activity: 'adventure',
    rating: 1,
    price: 1800,
    coverSrc: '/images/places/sea.jpg',
  },
  {
    id: 5,
    title: 'Tossin',
    desc: "abcd    ed",
    serviceTime: '25-30min',
    deliveryFee: 6.79,
    category: 'place',
    place: 'forest',
    food: 'chinese',
    activity: 'recreational',
    rating: 5,
    price: 2000,
    coverSrc: '/images/places/italiian.jpg',
  },
  {
    id: 6,
    title: 'stories noodles',
    desc: "abcd    ed",
    serviceTime: '5-15min',
    deliveryFee: 2.87,
    category: 'place',
    place: 'waterfall',
    food: 'italian',
    activity: 'recreational',
    rating: 5,
    price: 3500,
    coverSrc: '/images/places/fookyew2.jpg',
  },
  {
    id: 7,
    title: 'Nacho cheeseburger',
    desc: "abcd    ed",
    serviceTime: '50-65min',
    deliveryFee: 8.5,
    category: 'spot',
    place: 'mountain',
    food: 'bengali',
    activity: 'adventure',
    rating: 2,
    price: 2200,
    coverSrc: '/images/spots/nacho-burger.jpg',
  },
  {
    id: 8,
    title: 'Mushroom Risotto',
    desc: "abcd    ed",
    serviceTime: '10-15min',
    deliveryFee: 1.8,
    category: 'spot',
    place: 'forest',
    food: 'chinese',
    activity: 'adventure',
    rating: 1,
    price: 1900,
    coverSrc: '/images/spots/Mushroom-Risotto-Recipe-1-1200.jpg',
  },
  {
    id: 9,
    title: 'Shitake Fried Rice',
    desc: "abcd    ed",
    serviceTime: '12-18min',
    deliveryFee: 3.33,
    category: 'spot',
    place: 'waterfall',
    food: 'italian',
    activity: 'recreational',
    rating: 4,
    price: 2750,
    coverSrc: '/images/spots/shiitake-salmon-fried-rice-0218-103230720.jpg',
  },
  {
    id: 10,
    title: 'Pesto chicken stew',
    desc: "abcd    ed",
    serviceTime: '30-38min',
    deliveryFee: 1.9,
    category: 'spot',
    place: 'mountain',
    food: 'italian',
    activity: 'recreational',
    rating: 2,
    price: 4350,
    coverSrc: '/images/spots/pesto-chicken.jpg',
  },
  {
    id: 11,
    title: 'Bruschetta',
    desc: "abcd    ed",
    serviceTime: '16-20min',
    deliveryFee: 4.1,
    category: 'spot',
    place: 'forest',
    food: 'italian',
    activity: 'adventure',
    rating: 3,
    price: 3300,
    coverSrc: '/images/spots/as-tomato-bruschetta-articleLarge.jpg',
  },
  {
    id: 12,
    title: 'Dim Sums',
    desc: "abcd    ed",
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'spot',
    place: 'waterfall',
    food: 'chinese',
    activity: 'adventure',
    rating: 2,
    price: 4100,
    coverSrc: '/images/spots/dimsums.jpg',
  },
];

export const placeFilterList = [
    { id: 1, checked: false, label: 'Swimming Pool' },
    { id: 2, checked: false, label: 'BBQ Management' },
    { id: 3, checked: false, label: 'Beach Front' },
    { id: 4, checked: false, label: 'Free Breakfast' },
    { id: 5, checked: false, label: 'Fitness Center' },
  ];

export const foodFilterList = [
    { id: 1, checked: false, label: 'Bengali' },
    { id: 2, checked: false, label: 'Sea Food' },
    { id: 3, checked: false, label: 'Chinese' },
    { id: 4, checked: false, label: 'Italian' },
    { id: 5, checked: false, label: 'Veg' },
    { id: 6, checked: false, label: 'Non-Veg' },
  ];

export const activityFilterList = [
    { id: 1, checked: false, label: 'Adventure' },
    { id: 2, checked: false, label: 'Recreational' },
  ];

export const varList = [
  {PlaceName : "Sylhet",
   ComparisonType : "activity",
   bestTitle : ""},
];