# Generated by Django 4.0.6 on 2022-07-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Restaurant',
            fields=[
                ('food_restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRatingInfo',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('factor', models.FloatField(default=0, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('food_restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food_restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='FoodPriceInfo',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('food_restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food_restaurant')),
            ],
        ),
    ]
