# Generated by Django 4.0.2 on 2022-07-17 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spot.spottype_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile_Interests',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'interest')},
            },
        ),
    ]
