# Generated by Django 4.0.6 on 2022-07-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0005_user_spot_spot_type_spot_food_spot_activity'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spot.type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
