# Generated by Django 4.0.2 on 2022-07-14 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spot', '0006_placeratinginfo_end_time_alter_spot_place_id_and_more'),
        ('user', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
